server:
  port: 8081
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    target-service-key:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000